[package]
name = "hello-world"
version = "0.1.0"
authors = ["ImajinDevon"]
description = "A program/library to print a Hello World message to the standard output."
edition = "2021"

[dependencies]

[profile.release]
panic = "abort"
strip = "symbols"